version: '3.8'

networks:
  frontend-network:
    external: true
  backend-network:
    external: true

services:
  angular-frontend:
    labels:
      logging: "promtail"
      logging_jobname: "frontend_prod_logs"
    container_name: statsboards-frontend
    image: node:22.12.0
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run build --prod"

  angular-static-server:
    labels:
      logging: "promtail"
      logging_jobname: "frontend_nginx_logs"
    container_name: statsboards-frontend-nginx-static-server
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    volumes:
      - ./dist/statsboards-angular-legacy/browser:/usr/share/nginx/html
    ports:
      - "8383:8383"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - angular-frontend
    healthcheck:
      test: [ "CMD-SHELL", "curl -ks --fail https://localhost/front-nginx-health | grep -q 'Front Nginx is running'" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
