version: '3.8'

services:
  angular-frontend:
    container_name: angular-frontend
    image: node:22.12.0-slim
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run build --prod"

  angular-static-server:
    container_name: nginx-front-prod-container
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    volumes:
      - ./dist/statsboards-angular-legacy/browser:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - angular-frontend
    restart: always

networks:
  frontend-network:
    driver: bridge
  backend-network:
    external: true
